#!/usr/bin/env bash
set -ex

# format code
if [[ $CI ]]; then
    poetry run black --check .
    poetry run isort --check-only
else
    poetry run black .
    poetry run isort -y
fi

# lint
poetry run flake8 asyncio_redis
